### PR TITLE
added a notify on available button to MachineFragment.

### PR DESCRIPTION
**Pull request by bienzaaron**
Implemented it so that it gets the machine that has the least time left on it. 

Also, stuff got shifted around a bit because I ran IntelliJ's reformat code feature.

#22

### CODE REVIEW

**Comment by vidia** [comment]
Merge dev into this PR so we can get Travis to run checks please.

**Comment by hughesjeff** [comment]
Bump above comment

**Comment by hughesjeff** [comment]
I really apologize I haven't gotten around to this. I will review this today.

**Review by hughesjeff — APPROVED** [review]

**Comment by vidia** [comment]
I'm making a retroactive comment on this feature. I should have asked this before, but does this wait for the previous person to remove their laundry? And can we make it so that the button is only shown when all of the machines are currently taken? It would be great to be able to only have this in that case.

**Comment by hughesjeff** [comment]
No, this is just a timer that he did from what I can tell. Gets the machine with the least time and sets a timer based on it.

**Pull request merged**
