### PR TITLE
Filter Machines by Available

### PR DESCRIPTION
**Pull request by jpitlor**

### CODE REVIEW

**Comment by hughesjeff** [comment]
What if you only want to see ones that are almost done in case they are all in use? Add options to parse all 4 options. (Available, Almost Done, Running, and End-Of-Cycle) Make sure to add a default case in case it doesn't fall under those 4 categories. See setImage() in InformationActivity.java for how to parse the status of the machines and the default case.

**Comment by jpitlor** [comment]
Just to make sure I get it right the first time, since you're telling me to mimic setImage(), the default case is identical to case Running?

**Comment by hughesjeff** [comment]
Yep.

**Comment by bwencke** [comment]
This should use the filter list icon and always show as an icon in the action bar: https://www.google.com/design/icons/#ic_filter_list

**Comment by bwencke** [comment]
It would make more sense for the popup to have a list of all the states, each initially checked. The user unchecks states they do not want to see. Also, I do not know what end-of-cycle means or how that is different from almost done, so odds are users won't either.

filter

**Comment by jpitlor** [comment]
That last comment left me a little confused. I don't know what it means either, so are you saying just leave out Almost Done and let the method lump it with Running?

**Comment by hughesjeff** [comment]
No, he was saying that "End-of-cycle" is confusing. Maybe rename it to "Finished" or something. I can work on that.

**Comment by jpitlor** [comment]
Oh, ok. I'll implement it as I was and change it when you change how statuses work

**Comment by hughesjeff** [comment]
No no no, you just need to change your text for "End-of-cycle" to "Finished"

**Comment by jpitlor** [comment]
Should I be changing the statuses it checks for in preparation for your update too, though?

**Comment by hughesjeff** [comment]
I'm just gonna replace "End of cycle" with "Finished". But it won't affect your code at all. Still check for "End of cycle"

**Pull request merged**
